language: csharp
mono: none
dotnet: 3.0
script:
- dotnet test src
services:
- mysql
before_install:
- mysql -u root -e 'CREATE DATABASE tests;'
- mysql -u root -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'pass';"
- mysql -u root -e "GRANT ALL ON tests.* TO 'test'@'localhost';"