image: Visual Studio 2017

skip_branch_with_pr: true
skip_tags: true

install:
  - choco install dotnetcore-sdk --version 3.0.100

environment:
  Appveyor: true
    
services:
  - mysql

init:
  - git config --global core.autocrlf input
  - SET PATH=%POSTGRES_PATH%\bin;%MYSQL_PATH%\bin;%PATH%

build_script:
  - mysql -u root -e 'CREATE DATABASE tests;'
  - mysql -u root -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'pass';"
  - mysql -u root -e "GRANT ALL ON tests.* TO 'test'@'localhost';"

test_script:
  - cd src/FastInsert.Tests
  - dotnet test