image: Visual Studio 2017

install:
  - choco install dotnetcore-sdk --version 3.0.100

environment:
  Appveyor: true
  # MySQL
  MYSQL_PATH: C:\Program Files\MySql\MySQL Server 5.7
  MYSQL_PWD: Password12!
  MYSQL_ENV_MYSQL_USER: root
  MYSQL_ENV_MYSQL_PASSWORD: Password12!
  MYSQL_ENV_MYSQL_DATABASE: test
services:
  - mysql

init:
  - SET PATH=%MYSQL_PATH%\bin;%PATH%

before_test:
  - mysql -u root -e 'CREATE DATABASE tests;'
  - mysql -u root -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'pass';"
  - mysql -u root -e "GRANT ALL ON tests.* TO 'test'@'localhost';"

build: off

test_script:
  - cd src/FastInsert.Tests
  - dotnet test