image: Visual Studio 2017

install:
  - choco install dotnetcore-sdk --version 3.0.100

environment:
  Appveyor: true
services:
  - mysql

init:
  - SET PATH=%MYSQL_PATH%\bin;%PATH%

before_test:
  - mysql -e "create database tests;" --user=root

build: off

test_script:
  - cd src/FastInsert.Tests
  - dotnet test