image: Visual Studio 2017

install:
  - choco install dotnetcore-sdk --version 3.0.100

environment:
  Appveyor: true
  # MySQL
  MYSQL_PATH: C:\Program Files\MySql\MySQL Server 5.7
  MYSQL_PWD: Password12!
  MYSQL_ENV_MYSQL_USER: root
  MYSQL_ENV_MYSQL_PASSWORD: Password12!
  MYSQL_ENV_MYSQL_DATABASE: tests
services:
  - mysql

init:
  - SET PATH=%MYSQL_PATH%\bin;%PATH%

before_test:
  - mysql -e "CREATE DATABASE tests;" --user=root

build: off

test_script:
  - cd src/FastInsert.Tests
  - dotnet test

deploy:
- provider: NuGet
  on:
    branch: master  
  api_key:
    secure: RoAi8N5E0Reb5EmfE6VkpGFvSkXyi9ZjGzlqJSVU+WVZCo0qdixvxKdA5SBD0VYB
  skip_symbols: true
  artifact: /.*\.nupkg/
